### ISSUE TITLE
Multiple streams over a same socket

### ISSUE THREAD

**Issue by AaronO** [nkzawa/socket.io-stream#9]
I don't really have a snippet to reproduce this yet, that'll have to wait a few days since I'm very busy on other projects (for my Startup).

In one of the applications that streams terminals over socket.io-stream, I seem to have an issue when trying to open multiple streams over the same socket.

Do you have an idea where this is coming from ?

**Comment by huayun321** [comment]
upload multiple image at same time ?

**Comment by Gottox** [comment]
I get this issue with node-webterm. As soon as I open three or more streams in parallel they all stop working.

**Comment by nkzawa** [comment]
How can we reproduce the issue? Just sending three streams in parallel has no problem as far as I test.

**Comment by hirokith** [comment]
I've also encountered the same issue:

```
2020-05-08 17:14:03,334 ERROR 68491 nodejs.TypeError: Cannot read property '_read' of null (uncaughtException throw 1 times on pid:68491)
    at IOStream._read (/Users/dickeylth/dev/gitlab/edith/node_modules/_socket.io-stream@0.9.1@socket.io-stream/lib/iostream.js:97:15)
    at IOStream.Readable.read (_stream_readable.js:492:10)
    at resume_ (_stream_readable.js:977:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

pid: 68491
hostname: bogon
```

I'll try to create a mvp for reproducing the issue later.
